<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amonthpicker-1017-prevEl</name>
   <tag></tag>
   <elementGuidId>bcba773a-69eb-4927-b507-4ff01daf201f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='monthpicker-1017-prevEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthpicker-1017-prevEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d4ec6e3-9b16-4d20-ad28-caf4f9296f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthpicker-1017-prevEl</value>
      <webElementGuid>16bab62a-d51c-4d1f-9fb5-662d60d1c28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>prevEl</value>
      <webElementGuid>cd81c92c-7ed5-44a6-a9db-2746363f3db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-yearnav-button x-monthpicker-yearnav-prev x-unselectable x-monthpicker-yearnav-prev-over</value>
      <webElementGuid>a9f6f92e-f32f-4d1f-9aa7-453ad0e33b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d7a8add4-0281-484f-8185-64b39aa05b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49ec7ba3-58da-4e8a-9efc-a7762c8acd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-prevEl&quot;)</value>
      <webElementGuid>1de803ea-3c8d-4545-aca7-8d9875c2e80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>1acc79a2-9c52-40ac-946b-b1c75e124811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='monthpicker-1017-prevEl']</value>
      <webElementGuid>6d375c5c-f64f-4439-b37c-ce60f4b40280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div/div/a</value>
      <webElementGuid>cd32ce88-77e7-4380-af6d-979c1a16ad0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>bcac8875-b1d8-4f14-8888-d5e945acb6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'monthpicker-1017-prevEl']</value>
      <webElementGuid>47793d38-6cf1-4613-bdf1-802db4afef10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
