<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_24</name>
   <tag></tag>
   <elementGuidId>1d7a3666-c46a-4169-99ac-c3b125ff5c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='Date_Birth-picker-cell-25']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-picker-cell-25 > div.x-datepicker-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80cf8e41-506e-4b7c-9f78-b7bb52c2a83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f295fcd6-6678-4703-a6fc-7797fcf8a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-datepicker-date</value>
      <webElementGuid>b4e7a45b-23e1-4a58-b9d3-fb9111268bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>f5fea3dd-2bc0-40a3-b62d-20cfdd6183ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-picker-cell-25&quot;)/div[@class=&quot;x-datepicker-date&quot;]</value>
      <webElementGuid>f6664757-f7c5-453c-a4d7-e837d4c91341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>0348824a-478b-4e83-a4a4-209cf0ad6bd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='Date_Birth-picker-cell-25']/div</value>
      <webElementGuid>01246774-4ae5-4d03-9158-681ee3101add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/div</value>
      <webElementGuid>8095c36c-07b8-414e-91ef-271d6bf22831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '24' or . = '24')]</value>
      <webElementGuid>dca58515-481d-4e0d-88fc-0d8bc576be4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
