<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_x-monthpicker-yearnav-button-ct</name>
   <tag></tag>
   <elementGuidId>3dbc7778-abc0-476c-8ca4-2b0e85c0c8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monthpicker-1017-yearEl']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x-monthpicker-yearnav-button-ct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>639a4b67-207a-4822-b29f-774cedca7ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-yearnav-button-ct</value>
      <webElementGuid>d9f9cc29-d6e6-4113-b27c-a21d28066bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-yearEl&quot;)/div[@class=&quot;x-monthpicker-yearnav&quot;]/div[@class=&quot;x-monthpicker-yearnav-button-ct&quot;]</value>
      <webElementGuid>34f0318d-f4df-48bb-a411-f07053db6a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>06ffc55f-2f05-4dec-af92-2156318e57b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div/div</value>
      <webElementGuid>2d142a24-ce59-4452-a830-6d942a0dde5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>1b238f81-89bd-4edb-b59b-bf804b927b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
