<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_FK_Multi_District_Co_a8f754</name>
   <tag></tag>
   <elementGuidId>8e2ca61c-8244-48ad-bfbc-1820d9e15e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62145854-023b-4408-9ea6-5aaddb3f2f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      <webElementGuid>cf75ecf2-d31f-4558-9285-070fc1b184a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-simplearrowdown-trigger x-form-simplearrowdown-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>0662fab5-5efa-4cfb-94ac-d1940150cc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a1a40aa3-3abf-41f7-9ec3-e3e8742e17be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker&quot;)</value>
      <webElementGuid>9e094558-4ab4-45fd-b7ad-948631ef9e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>55ead023-92e2-487f-ad03-ad636377f93f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>4d112b3a-7a98-43d8-885d-64b094c90e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-triggerWrap']/div[3]</value>
      <webElementGuid>24c57ddb-c25f-49ac-a89c-e799120cc4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>97970d7e-55ee-4b27-9d16-dde603af7aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>e49d722c-daaa-4bdb-b83f-818581dcb5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
