<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divDate_Birth-trigger-picker</name>
   <tag></tag>
   <elementGuidId>7d7138c8-e6d1-4e48-8513-d21d80f4ff1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Date_Birth-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27d05c42-de9c-42f0-b592-1cec8bad8969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Birth-trigger-picker</value>
      <webElementGuid>8259f150-0b4c-4afc-8e8a-b02f7e1263e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-date-trigger x-form-date-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>0084134f-97f4-47d1-82dc-30c2308600f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>97b72dce-0c52-4db3-a8d7-32553d7c64d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-trigger-picker&quot;)</value>
      <webElementGuid>5e47894a-88f5-4d7e-bfe5-63650feb8c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>ec94a561-fe23-45ff-aa39-e4f2d924e542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-trigger-picker']</value>
      <webElementGuid>9a5b355a-3880-4236-bc9c-d9d69a50885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-triggerWrap']/div[2]</value>
      <webElementGuid>25b5e845-44f1-455f-90c8-2f533dc3ef0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>aa209ed1-63d2-4b9d-8a77-a1fe5b27208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Date_Birth-trigger-picker']</value>
      <webElementGuid>2c569af9-2d03-4f74-bee0-795b99122e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
