<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divtool-1045-toolEl</name>
   <tag></tag>
   <elementGuidId>a2f8d3aa-ce2e-4a39-bc29-a2b5fe04ba4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tool-1045-toolEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tool-1045-toolEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b40ebe2f-5a46-400c-b9bc-e10b79441fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-1045-toolEl</value>
      <webElementGuid>945dab30-6044-4a32-838b-5887ea4050d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>toolEl</value>
      <webElementGuid>09a0a581-872e-4908-808a-41829566ac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tool-tool-el x-tool-img x-tool-close </value>
      <webElementGuid>76c9288c-100a-4f3f-80cd-e463c6149d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b43d49dc-2ba1-4f88-aef8-177c19c15e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-1045-toolEl&quot;)</value>
      <webElementGuid>20ae3f47-331c-47e6-b4cb-bb9b3aa15baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>2ae4dcd5-3e3b-4af6-a505-414b2cc1d026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tool-1045-toolEl']</value>
      <webElementGuid>b74df16e-e322-4b2e-82d7-41bd2778c871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tool-1045']/div</value>
      <webElementGuid>3186ffd2-13a7-44aa-8dde-594d79e0ee46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[4]/div</value>
      <webElementGuid>d76bfeb4-23ae-4091-a051-d9be63307136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tool-1045-toolEl']</value>
      <webElementGuid>90b3558a-ab40-4412-8c80-255e16ec7697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
