<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_D004 - Jakarta Pusat</name>
   <tag></tag>
   <elementGuidId>e37d9103-c71d-450e-b277-565bb7296647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8fab61b9-7001-4c77-93c1-1fbf9654d066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>23e0abc2-2561-46bd-915f-712035e18be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>08fb0bca-9292-4b78-ab9e-706c2dbf5a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>548beebb-3b39-4468-9266-f79fbc7241f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bbd3c877-b235-47af-a8cf-1ae01e033ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e384498e-103b-4059-95e8-f14134b672bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e33520a0-7dc7-46e8-b686-edf57214ecd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>FK_District_Code-picker</value>
      <webElementGuid>caa8300e-4862-48da-a15a-9062368899f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-24</value>
      <webElementGuid>4c15e623-874b-4980-94d6-1247c723c970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D004 - Jakarta Pusat</value>
      <webElementGuid>1403e6d9-c7db-48b7-817d-ad31ea95262b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-24&quot;)</value>
      <webElementGuid>89e4dd84-7efa-43bd-822d-733aae18ee2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>58ef4a4d-62f4-4ffe-999b-03b6caf7b017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-24']</value>
      <webElementGuid>3b8ad45d-b50b-486e-a4c9-8d9452023bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='FK_District_Code-picker-listEl']/li[4]</value>
      <webElementGuid>c594e2a4-d606-4654-9d71-48324fa41440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>56c860ce-9deb-4f75-b234-b34621045697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-24' and (text() = 'D004 - Jakarta Pusat' or . = 'D004 - Jakarta Pusat')]</value>
      <webElementGuid>625b6962-88f5-4bea-8c5e-d0764877d3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
