<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_December 2023</name>
   <tag></tag>
   <elementGuidId>701c4364-a6e0-4676-95c9-0ede23bb7e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#splitbutton-1014-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39d9cfe1-9254-4631-b4b7-2128924ccbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splitbutton-1014-btnInnerEl</value>
      <webElementGuid>2b6da0d9-9a8c-4176-b00d-08b849d80940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>5789fd72-f288-4bc7-b5e4-4dee1a68c711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>453353e2-abf3-4f98-b19f-cca8a2a30e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-small</value>
      <webElementGuid>0d4dd4b6-6111-4c7c-bae7-be3773646107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>December 2023</value>
      <webElementGuid>2faa8d77-5ee3-480e-8718-0cc1bcc49e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splitbutton-1014-btnInnerEl&quot;)</value>
      <webElementGuid>a8b08187-6bc4-41b6-8f68-5c7b7a78c8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>8e3bf9a0-538a-4258-b5cb-c274ffae4fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      <webElementGuid>02ae5558-1f15-451d-8e2d-0b83d5309d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnEl']/span[2]</value>
      <webElementGuid>dd87b2a3-9610-42a5-bac3-1498a62b4e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/a/span/span/span[2]</value>
      <webElementGuid>53d7280a-a9af-4c39-8df6-f64b2dab24af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'splitbutton-1014-btnInnerEl' and (text() = 'December 2023' or . = 'December 2023')]</value>
      <webElementGuid>de6f366c-a020-4304-a4ac-9eb29f3e12d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
