<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add New Record</name>
   <tag></tag>
   <elementGuidId>f3357d44-7e84-4f45-8a0b-2b8728b825d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BtnAdd-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnAdd-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc8d3e2b-49b1-45a3-a551-a70803066639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnAdd-btnInnerEl</value>
      <webElementGuid>9c40a60a-65e8-4fdc-9e46-fe1d69e1d2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>ae7bc421-6c39-4fc9-a7f5-779a5eac67f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f43906d1-4683-43ff-b8c2-cded2c900616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>706fe8ee-644a-495b-9e79-54315d57c04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Record</value>
      <webElementGuid>4482375a-fbe0-4ef1-bf01-de83e6336ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnAdd-btnInnerEl&quot;)</value>
      <webElementGuid>7b0b8bcc-dbf3-4fc8-8eb8-b75ce0a3b90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>ec8ac843-1f14-4795-8b27-b9664fbc1b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BtnAdd-btnInnerEl']</value>
      <webElementGuid>5999a920-d365-4559-bcd8-45f285085dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='BtnAdd-btnEl']/span[2]</value>
      <webElementGuid>c144d13a-2512-40ba-a24d-0b32df34b591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span/span/span[2]</value>
      <webElementGuid>76ce28d6-17b3-4b2b-82e4-2407da9f7ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BtnAdd-btnInnerEl' and (text() = 'Add New Record' or . = 'Add New Record')]</value>
      <webElementGuid>17f6b48c-bbd9-481c-b8ae-c7c930748034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
