<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK</name>
   <tag></tag>
   <elementGuidId>bdf9b1da-bba4-40e0-8513-85c37f7c7d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1018-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1018-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59d567be-6835-4d31-be42-3ff6e2070084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1018-btnInnerEl</value>
      <webElementGuid>62e48b5a-edf8-421f-9cfa-19dcf162e099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>1c1b317d-ab99-4993-98a7-0130c651298c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>cbeda114-db4f-49fc-906c-be3814bf5346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-small</value>
      <webElementGuid>99136edc-53b0-4aea-a0b4-b4098558e061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>1f5c34d9-1ee6-433f-97f3-02d0564a550f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1018-btnInnerEl&quot;)</value>
      <webElementGuid>0481c72b-1952-4d12-9b11-09449eb31571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>323c5f4c-01ca-4210-979e-56a5fba6bfe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1018-btnInnerEl']</value>
      <webElementGuid>d75eb71e-6596-45b8-9dea-dc0591dbe7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1018-btnEl']/span[2]</value>
      <webElementGuid>d9c0bd4c-f704-4923-98ab-b60a884bb959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/span/span/span[2]</value>
      <webElementGuid>fe8a32a7-0ede-47b5-a025-36171050bf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1018-btnInnerEl' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>8087cbd2-eca0-4657-ac67-bcc652cbfafa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
