<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_cboExportExcel-trigg_294ccd</name>
   <tag></tag>
   <elementGuidId>7fd182d2-88a5-4543-a03d-f85d93902070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_cboExportExcel-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_cboExportExcel-trigger-picker</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'ContentPlaceHolder1_cboExportExcel-trigger-picker' and @ref_element = 'Object Repository/downloadtransaction/iframe_nodeundefined_IFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbefd288-553c-4d52-946d-7a31f2ed30c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_cboExportExcel-trigger-picker</value>
      <webElementGuid>55aaa320-09ed-48f6-8d58-ab21231a101e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>51e1b281-ca94-4ead-865a-51cd05dfd69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3ebcc8ff-f5cf-4149-8462-5c1aadfe25e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_cboExportExcel-trigger-picker&quot;)</value>
      <webElementGuid>b1875244-4199-4264-ba24-b43971db0d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/downloadtransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>9878c4da-fa40-45b7-9156-d686e9d93486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_cboExportExcel-trigger-picker']</value>
      <webElementGuid>5ed2ca81-76c4-4f55-bc25-7d4d54b3c83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_cboExportExcel-triggerWrap']/div[2]</value>
      <webElementGuid>1b6e8c62-14f0-4f1f-8a5b-0168c08747f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>09d66bf5-467c-4385-8c3e-7564bd98fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_cboExportExcel-trigger-picker']</value>
      <webElementGuid>2f45ae58-069c-4018-b113-56a1f86e8ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
