<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CSV</name>
   <tag></tag>
   <elementGuidId>ad71f22d-f93f-4253-b604-787dde6e5a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'CSV' or . = 'CSV') and @ref_element = 'Object Repository/test/iframe_nodeundefined_IFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-73']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-73</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3339e07e-1cd6-4e3c-807c-f8f03afdb25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8c01112a-82ee-44e4-ad21-4698ad1e0f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b0318172-1827-49ba-a979-7a52904c34fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-selected x-boundlist-item-over</value>
      <webElementGuid>4bae5f0b-2237-4835-af4c-df9182658d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25f7e0ae-ec7b-4be3-b90e-54b10b4ccfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4e673a36-07b2-41f4-9f18-1de2c7230756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fab405d4-3fad-47af-a428-276ba206d8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_cboExportExcel-picker</value>
      <webElementGuid>ceaf4bb6-f6a6-467f-b776-4dc3abf933ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-73</value>
      <webElementGuid>102d39ed-2117-4609-84bd-35ab37061dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>76304e9b-2677-4f5c-a415-afe8606d537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-73&quot;)</value>
      <webElementGuid>ac1928e1-a65d-4db2-aaa7-bfe71cefdecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-73']</value>
      <webElementGuid>c8cc398b-5abf-473b-a5bf-f0a340565861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContentPlaceHolder1_cboExportExcel-picker-listEl']/li[2]</value>
      <webElementGuid>53a2f943-1ae0-4bb5-88b4-f857eafe5524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>810d37d1-c1c0-47e4-81d4-a51e020667ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-73' and (text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>1032aff8-fae8-4aed-beac-d18a09cd1c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
