<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Export Current Page</name>
   <tag></tag>
   <elementGuidId>453307fc-d871-4337-90a4-ac36624642e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BtnExport-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnExport-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb685f68-4eb2-4917-b564-84dbef420e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnExport-btnInnerEl</value>
      <webElementGuid>acb603a3-624a-4388-a96c-00dbb5e9bb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>47354987-6495-421b-afcd-de9b28ac7bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>25dd7550-9867-4380-85d6-ac17e0c8a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>c047513b-debb-4f38-aed2-1f8a5cbc570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export Current Page</value>
      <webElementGuid>39ee46e2-697b-4b5b-ab9f-ac705b457c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnExport-btnInnerEl&quot;)</value>
      <webElementGuid>feae1ece-5055-463a-ade2-1dc17ea76886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/downloadtransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>7292a1c6-7716-43cd-8628-039af55233c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BtnExport-btnInnerEl']</value>
      <webElementGuid>4524f759-ea40-4deb-b1e0-696f465720cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='BtnExport-btnEl']/span[2]</value>
      <webElementGuid>40d3c797-240c-4d7c-92d6-754d9238f0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>814355e1-ca37-4572-96bf-071789de6878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BtnExport-btnInnerEl' and (text() = 'Export Current Page' or . = 'Export Current Page')]</value>
      <webElementGuid>8deb983c-d9d9-438d-9b72-660e032a78f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
