<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amonthpicker-1017-prevEl</name>
   <tag></tag>
   <elementGuidId>0b018c2d-7cd2-40ba-b96c-0007a9c96a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='monthpicker-1017-prevEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthpicker-1017-prevEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24071d73-1ff0-4646-be21-03c5d7e073e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthpicker-1017-prevEl</value>
      <webElementGuid>8d29cfe3-670f-4655-b171-c4115e22470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>prevEl</value>
      <webElementGuid>eae13e2a-9b83-47f2-9792-ef7b7ea9137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-yearnav-button x-monthpicker-yearnav-prev x-unselectable x-monthpicker-yearnav-prev-over</value>
      <webElementGuid>f4e62e92-dbce-4904-8e8b-55440baaa495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b6b3da18-b029-4601-960f-dab56db0d9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1917cd3c-dd70-43bb-ae60-1f36f8015d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-prevEl&quot;)</value>
      <webElementGuid>e545c229-087f-486d-8d3e-b0642fb6bcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>ec9612eb-2558-424b-8d9b-01ffffc9808b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='monthpicker-1017-prevEl']</value>
      <webElementGuid>6879ef62-8568-43c7-bc73-c16b02ed92a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div/div/a</value>
      <webElementGuid>8bc4d39b-9c66-4639-94a2-6fd852f048af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>15ca6a41-b7c2-4047-adf7-b508c4b43cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'monthpicker-1017-prevEl']</value>
      <webElementGuid>8b4f7457-0d67-4efb-a3fe-c0f8b2ceab28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
