<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_24</name>
   <tag></tag>
   <elementGuidId>da60ad4f-26ae-4556-abc9-6af1551310fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='Date_Birth-picker-cell-25']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-picker-cell-25 > div.x-datepicker-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81a05e8f-5b21-4ac5-8219-83bd6991e106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d270c4c2-fa4f-4052-89fc-61a6ae9aea2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-datepicker-date</value>
      <webElementGuid>1c461982-9d5c-4a44-bdae-a006812c3a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>0d65aabc-1389-4aa7-814b-94c18975796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-picker-cell-25&quot;)/div[@class=&quot;x-datepicker-date&quot;]</value>
      <webElementGuid>66edd05e-6861-425d-a260-68835d91041f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>46f4655c-9c9f-450c-99be-ec3906a7fb7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='Date_Birth-picker-cell-25']/div</value>
      <webElementGuid>9a853d6a-938a-4a92-bcd9-5acd63131275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/div</value>
      <webElementGuid>b201c707-eb65-4b32-b14d-a0d9f494873a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '24' or . = '24')]</value>
      <webElementGuid>ee0421d6-f133-420f-a7ec-72d12aba12f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
