<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_FK_Multi_District_Co_a8f754</name>
   <tag></tag>
   <elementGuidId>6d8644fd-8aae-423f-8554-b791058f67a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3cb08d6-6f5a-4eff-b08d-cb83e8fe13a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      <webElementGuid>6de726dd-756d-4792-b02c-54f9c3e66795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-simplearrowdown-trigger x-form-simplearrowdown-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>b6d89855-db96-4da1-a9ba-f601d6e19957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>79687af6-6bb3-4d47-ad94-4626edd83826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker&quot;)</value>
      <webElementGuid>c4f30784-9300-4a4e-a1eb-3616cb3dbee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>339caf50-5679-4ada-b003-6950439ca476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>fd127bab-be65-435b-bfb3-72495050185e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-triggerWrap']/div[3]</value>
      <webElementGuid>ef6e31a5-8467-4abb-858e-c0b489040854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>d4597e43-6378-4a22-9751-a6f8a2340312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>b41c17e3-8f0e-4835-91e0-34167a7e6eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
