<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divDate_Birth-trigger-picker</name>
   <tag></tag>
   <elementGuidId>7c23884d-0571-4f9e-b91f-cdb2f73d0c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Date_Birth-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a8e550b-95e6-48d7-916d-79830345512f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Birth-trigger-picker</value>
      <webElementGuid>9d8c75a4-684c-4fd2-a7ac-83bf533cb6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-date-trigger x-form-date-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>6acca727-768d-4561-ae15-bd8fd7b68f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ef09105d-d64c-4151-b91a-89bc1a28aa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-trigger-picker&quot;)</value>
      <webElementGuid>2f2ff80e-8f65-4250-9d87-2c6e13aa10dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>c0bbbefb-88b0-40fb-a23d-b73d08bd313d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-trigger-picker']</value>
      <webElementGuid>82050974-5794-487d-9386-d5f6b6b6f104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-triggerWrap']/div[2]</value>
      <webElementGuid>06f6d56d-9790-4251-9de8-79e1c3c2107e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>a2fb0d32-2ffa-40b1-9c7f-03cf8376db04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Date_Birth-trigger-picker']</value>
      <webElementGuid>ddeee70a-f61c-4005-9922-f150a2675b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
