<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divtool-1045-toolEl</name>
   <tag></tag>
   <elementGuidId>7e7efc9c-1919-4f51-ab49-fbdc71cebe9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tool-1045-toolEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tool-1045-toolEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a965bc4b-5d2e-4412-a897-b4a4f2d9a049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-1045-toolEl</value>
      <webElementGuid>e3b7840e-9e05-4eef-9de0-c68c75bd75d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>toolEl</value>
      <webElementGuid>0ebbacbc-369a-4c6f-8ff3-6b09b4829f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tool-tool-el x-tool-img x-tool-close </value>
      <webElementGuid>42f87ab8-869f-48ab-a3d1-0a8edff011cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6d799fe8-e590-40f5-88fe-52cb75d304b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-1045-toolEl&quot;)</value>
      <webElementGuid>81795565-78dd-4b78-86ce-5135da8b6810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>5e9847ac-0183-4bce-bdac-45f9b501d200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tool-1045-toolEl']</value>
      <webElementGuid>a501f724-d200-4092-bff4-27284ed74d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tool-1045']/div</value>
      <webElementGuid>126141a2-154e-433a-bebd-b75cb09794bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[4]/div</value>
      <webElementGuid>a51772e9-8298-4cf2-9625-30b81cefbfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tool-1045-toolEl']</value>
      <webElementGuid>dcd1233a-0b99-43be-bc1f-0222376dde41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
