<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_D010 - Jakarta Barat</name>
   <tag></tag>
   <elementGuidId>f24adeb5-9527-4dbd-a264-a6727324b347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ad0589d8-5338-4107-a843-1f01b7ca082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>86006fdd-228f-4ee5-ab4e-9345c62b2b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>9898b0ef-0d94-41a7-b335-192e763d3271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>80b760ba-5db8-4ed4-aef4-100a1f838ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dad72990-be73-4a19-a31e-8b5fa6fd4077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2c1cc2ae-0a68-4ac1-8e1a-4365f59eef88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f432bb92-6b38-4ffe-8c37-c5b28e531268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>FK_District_Code-picker</value>
      <webElementGuid>2f92892a-5f26-4237-a0ec-7963ca9c53e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-23</value>
      <webElementGuid>2651d07f-b962-44c7-b4df-33a74b22b9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D010 - Jakarta Barat</value>
      <webElementGuid>c783a4bb-0420-451d-97f4-ec3e5db9d087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-23&quot;)</value>
      <webElementGuid>c08b5ff8-d48a-4816-b911-4428c1577b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>a7760943-d164-4af0-869f-53bf01c792cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-23']</value>
      <webElementGuid>f0911cf5-d3a8-4ad1-ab41-a11502ccd3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='FK_District_Code-picker-listEl']/li[10]</value>
      <webElementGuid>7945de0a-a4f5-4d7b-8d4b-800717e85985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]</value>
      <webElementGuid>9238ff62-84c0-411f-99e9-196cc8eb6f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-23' and (text() = 'D010 - Jakarta Barat' or . = 'D010 - Jakarta Barat')]</value>
      <webElementGuid>16f426af-aa03-4f56-a396-5f820d83a81c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
