<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_December 2023</name>
   <tag></tag>
   <elementGuidId>5480c546-c241-4931-b215-a6d6016a442b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#splitbutton-1014-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>731745e1-0e63-432c-bcea-f7b23ae4c265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splitbutton-1014-btnInnerEl</value>
      <webElementGuid>805358d0-d300-4e31-96b8-e2a0bbd2fd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>cfbcf71e-dcd1-4bde-993d-8b5d30568720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>85b6fa5c-f40c-4a55-b5a3-caf6be90e05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-small</value>
      <webElementGuid>592f285b-f9fa-43f6-b475-414167e481e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>December 2023</value>
      <webElementGuid>e0ad1788-6848-40ed-be09-fd9081c0908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splitbutton-1014-btnInnerEl&quot;)</value>
      <webElementGuid>04aa486f-b9dd-43cc-bcef-03e947d058cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/addnewrecordsuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>74eccdc0-8dd7-440c-8a7e-94867799fafb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      <webElementGuid>6ae40db2-ff7f-4d7e-990c-bbed65fd661e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnEl']/span[2]</value>
      <webElementGuid>c5509e2b-2e4b-48fd-8e21-7fe28ba8b5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/a/span/span/span[2]</value>
      <webElementGuid>1e48dd1b-771b-439a-ab26-c66f745bf6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'splitbutton-1014-btnInnerEl' and (text() = 'December 2023' or . = 'December 2023')]</value>
      <webElementGuid>db76aa19-dd47-4cac-8f07-235fab6cc0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
