<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_AdvancedFilter1_cboF_ea7e77</name>
   <tag></tag>
   <elementGuidId>83c82bf1-367b-47ef-a400-1a3eaedd39e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f439cc8-0a89-4950-b6e9-77c1ac470ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker</value>
      <webElementGuid>c5bac0af-15da-4d7b-9173-5b7a62cb343f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>367f2feb-9d9d-4a5d-887e-14a4b0a0f5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>02148ed1-c246-4c16-97d4-c97b7c9f95b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker&quot;)</value>
      <webElementGuid>b9ed4faf-052e-42f8-949e-d162eded02ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/advancedfiltersuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>aa89f36f-390d-4a26-a23c-adcbf293b705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker']</value>
      <webElementGuid>1a684a95-af9f-4294-98fa-28d51c11502f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-triggerWrap']/div[2]</value>
      <webElementGuid>046f3ce9-ceb5-4ccd-a3e3-ab129cb01dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>0bad6f7e-e8d8-4ffc-acc9-ebe7e9a4063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker']</value>
      <webElementGuid>f18271de-80f2-4af3-91b1-81129267bd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
