<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_nodeundefined_IFrame</name>
   <tag></tag>
   <elementGuidId>f143b4e1-ea0d-4f15-bf4f-56dcc402e556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1031']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#component-1031</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name = 'nodeundefined_IFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>77a0e1ab-f3b8-42d6-bef7-d218a5d5a70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-component-default</value>
      <webElementGuid>e705c6ab-c033-4ad5-ac58-8be4053e7732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1031</value>
      <webElementGuid>8dbce81c-f92d-4128-bdca-40334fead938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeundefined_IFrame</value>
      <webElementGuid>d5e4920a-e7d8-4981-ad3e-565f1be0eda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1703232890236</value>
      <webElementGuid>cb07e4a6-0743-43bf-94da-57d7971a9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d257a6e-cb4e-48dd-a8cb-e55fefea8bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1031&quot;)</value>
      <webElementGuid>0373ade9-8345-432e-bff7-1d7108579910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1031']</value>
      <webElementGuid>ea1bbe86-e4b3-4fa4-b467-47177d998678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nodeundefined-body']/iframe</value>
      <webElementGuid>c0189a4c-d8d0-498d-89d9-8cab71a7874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7d3d108a-3e11-4725-9129-005ad07294ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1031' and @name = 'nodeundefined_IFrame' and @src = '/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1703232890236']</value>
      <webElementGuid>e8c3f7b7-972e-41bd-95d7-23e9709ae733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
