<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_District</name>
   <tag></tag>
   <elementGuidId>a3f02457-6865-40da-a8d6-f078aab137e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-120']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-120</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'District' or . = 'District') and @ref_element = 'Object Repository/advancedfiltersuccess/iframe_nodeundefined_IFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f16315d4-8e7c-42c5-853c-722a1ba4e20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8f90f137-a08d-4446-89f9-0d50a7785294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4adffd6e-b227-4c8d-af24-e20916121a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>081c21cb-8611-47ad-a120-59fa6236397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>26c6e2be-eb4a-4944-a1fa-3f81761e94dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2a0bec50-acab-4ef8-a9b9-9c00ab9cbe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>109</value>
      <webElementGuid>c9cdb547-1e32-4e6d-8950-0b4c0c132a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboField-picker</value>
      <webElementGuid>6d82ee9b-5fcc-410f-859c-0cc7760635e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-120</value>
      <webElementGuid>8d15f2e4-91d3-4fac-9c17-ca7833df7fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>District</value>
      <webElementGuid>42bcf37f-e2e8-4656-b42e-2ecae2bf8ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-120&quot;)</value>
      <webElementGuid>aaecbb6b-368f-4b66-af2e-0e80a71e7e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/advancedfiltersuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>2a892472-fdef-410f-83b5-3011c60d5b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-120']</value>
      <webElementGuid>3c5f0694-29cd-45a1-bcb6-59d447345622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-picker-listEl']/li[5]</value>
      <webElementGuid>9d648f2f-739b-40a8-b89c-b1ef53a8eb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>471d51b8-0dbf-4a41-9b6c-9ce12f46651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-120' and (text() = 'District' or . = 'District')]</value>
      <webElementGuid>7cbd098e-a43c-4c5f-8b3b-b6ee46370f4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
