<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Employee Name</name>
   <tag></tag>
   <elementGuidId>3e029c1a-d154-48db-9429-fdb3ac1d245f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-77']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-77</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Employee Name' or . = 'Employee Name') and @ref_element = 'Object Repository/advancedfiltersuccess/iframe_nodeundefined_IFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>efee670f-dd58-44e0-bd77-a71301d6485f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>37ec4a6a-070f-4d27-bbfe-26a792824866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>50245d4a-def3-4fec-87e2-4db154182411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>5fb7ed14-1d6d-4874-8d8b-27b3740daf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e185f248-5844-4478-ade1-4bf650b0934f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>11ff3e89-7892-4112-9a2b-0128e3bd67bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>e345d942-486d-4c73-b1a8-f837696cb4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboField-picker</value>
      <webElementGuid>b49b641a-97b4-4be7-b752-017d2ce04434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-77</value>
      <webElementGuid>8bb1a8ff-460c-4f9c-adf8-f05592a64f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee Name</value>
      <webElementGuid>cb76349d-834e-4e39-aeab-80bc81cc572a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-77&quot;)</value>
      <webElementGuid>632a7af1-5480-4101-9f92-86b6467b7ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/advancedfiltersuccess/iframe_nodeundefined_IFrame</value>
      <webElementGuid>8509d94f-6e4e-4dff-88e6-e2441e65c037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-77']</value>
      <webElementGuid>9dc4d2e2-c322-463b-97c0-b40ee77dde6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-picker-listEl']/li[2]</value>
      <webElementGuid>1c92295b-036a-49c3-b89a-f627be749026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>5982e86a-8237-4919-a58f-c158273326b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-77' and (text() = 'Employee Name' or . = 'Employee Name')]</value>
      <webElementGuid>d564ffcc-321d-495d-8f14-d2b2f219efb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
