<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_FK_Multi_District_Co_a8f754</name>
   <tag></tag>
   <elementGuidId>233afc09-dd10-4924-b315-f10ea748a797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c369639-fddf-4c08-9f83-b0ea2c3003f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      <webElementGuid>5942ab63-4a49-48ef-9fac-1a065392d4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-simplearrowdown-trigger x-form-simplearrowdown-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>288c0531-b9b4-4514-904d-750e984811d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>076961a9-cbd9-4883-8803-7dc6b1bfde55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker&quot;)</value>
      <webElementGuid>82d7999d-0742-40a8-81fc-4d227ec7b4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/edittransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>7797452d-4ba4-4a1b-bc64-2124c74c3f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>024ba79f-a501-4cd8-b037-ac005ce9bc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-triggerWrap']/div[3]</value>
      <webElementGuid>aec3df89-a9ac-4720-bb40-88549f853ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>e5d36859-8c59-49d4-bf63-0d117a0d0b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>3fb44188-6266-4159-9b72-16d847bcc718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
