<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divtool-1038-toolEl</name>
   <tag></tag>
   <elementGuidId>12e31bb0-9ab1-4540-a921-5d0cbfda7884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tool-1038-toolEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tool-1038-toolEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48928125-2c01-4797-80b4-b876cd3f392d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-1038-toolEl</value>
      <webElementGuid>2a11b05b-7ae5-4f14-ae4a-b32f1d2a203a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>toolEl</value>
      <webElementGuid>a247e8ea-44e5-4874-93ac-8288132d70ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tool-tool-el x-tool-img x-tool-close </value>
      <webElementGuid>12535541-025a-450d-aa86-85623371111a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6c0b89e7-868f-41d8-bef3-5c547b358908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-1038-toolEl&quot;)</value>
      <webElementGuid>03ab2bd8-9abe-480a-8b77-3b9e4dfab535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/edittransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>c5f9e78d-b45f-4d06-910a-73394a3c1c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tool-1038-toolEl']</value>
      <webElementGuid>74e5c809-8d7a-41d3-8c39-ff242ec66914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tool-1038']/div</value>
      <webElementGuid>895563a2-e32e-47c8-be51-54f6eabb93de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[4]/div</value>
      <webElementGuid>fa5d72bd-d5e2-4be4-9b7a-66a8a18939d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tool-1038-toolEl']</value>
      <webElementGuid>78dc4587-a74b-4a84-8577-d007a4897f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
