<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_x-grid-checkcolumn_1</name>
   <tag></tag>
   <elementGuidId>032e85cc-d56c-43e5-88d1-68d3b73ec380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tableview-1021-record-20']/tbody/tr/td/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1a73db5-72c7-4c31-95dc-3daf00c7d9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-checkcolumn</value>
      <webElementGuid>e3bd1bfb-9e90-4564-958a-b95e5a63957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df5e6b64-9122-4b32-8e0b-a0cc071b7a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c39bd192-8277-4f37-a469-37ac3e9b7730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableview-1021-record-20&quot;)/tbody[1]/tr[@class=&quot;x-grid-row&quot;]/td[@class=&quot;x-grid-cell x-grid-td x-grid-cell-checkcolumn-1039 x-grid-cell-special x-selmodel-column x-grid-cell-first&quot;]/div[@class=&quot;x-grid-cell-inner x-grid-checkcolumn-cell-inner&quot;]/span[@class=&quot;x-grid-checkcolumn&quot;]</value>
      <webElementGuid>e3f2ae9e-2b2d-4f6c-a0d4-15f4f988ba79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/edittransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>9ae3fdde-d03a-463d-86b7-42fd90a80f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableview-1021-record-20']/tbody/tr/td/div/span</value>
      <webElementGuid>e0ba4f47-4596-4c53-b11a-e8da8673744a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td/div/span</value>
      <webElementGuid>fe627a9f-deb3-470d-ad67-31bc9c6719e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
