<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_x-grid-checkcolumn</name>
   <tag></tag>
   <elementGuidId>3fbe2e5c-123f-4c32-934a-38d84f140bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tableview-1021-record-19']/tbody/tr/td/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29d85d5d-49ca-483a-88fd-dafb3a5417b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-checkcolumn</value>
      <webElementGuid>d10021f0-5ddf-4bcd-b481-2467f91248e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7fea35a-6a56-435b-8bcc-f2f8ef517635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71780ccb-dd71-4a06-863d-969def0d86ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableview-1021-record-19&quot;)/tbody[1]/tr[@class=&quot;x-grid-row&quot;]/td[@class=&quot;x-grid-cell x-grid-td x-grid-cell-checkcolumn-1039 x-grid-cell-special x-selmodel-column x-grid-cell-first&quot;]/div[@class=&quot;x-grid-cell-inner x-grid-checkcolumn-cell-inner&quot;]/span[@class=&quot;x-grid-checkcolumn&quot;]</value>
      <webElementGuid>ced79b79-9035-43cc-8f90-61a46e1baffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/edittransaction/iframe_nodeundefined_IFrame</value>
      <webElementGuid>63623d83-9a12-4b63-8913-d49e6a524e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableview-1021-record-19']/tbody/tr/td/div/span</value>
      <webElementGuid>4a2fe282-e926-4e54-ac57-96227cca05ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td/div/span</value>
      <webElementGuid>e3f1d3ac-01c7-4243-b400-ffcdb564a930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
