<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_nodeundefined_IFrame</name>
   <tag></tag>
   <elementGuidId>af4cd103-b19e-404a-9ec5-a744a4e046fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name = 'nodeundefined_IFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1031']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#component-1031</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4bd98444-87b8-4a34-a262-dcc891f0f4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-component-default</value>
      <webElementGuid>fdb53a3a-f393-4a9f-9b80-31af2795f505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1031</value>
      <webElementGuid>bc33bd8f-48a9-43c0-98a7-660f55b1c6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeundefined_IFrame</value>
      <webElementGuid>34b477c5-a885-4add-ba67-b2aa60c2435e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1703149948387</value>
      <webElementGuid>e2b04bc2-5711-4b7c-a46a-6d3d2ac73a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9b35b86c-f9fe-4c08-93d7-d7198c94826b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1031&quot;)</value>
      <webElementGuid>bbe284f7-1751-4ad7-a3fa-77451aea861e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1031']</value>
      <webElementGuid>b1cc9b46-f658-4669-b38e-cc581e4880b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nodeundefined-body']/iframe</value>
      <webElementGuid>50c5733b-ffab-429d-b1e9-fbb1e5dacbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f3010012-4422-4531-a72a-cc0e82acfb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1031' and @name = 'nodeundefined_IFrame' and @src = '/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1703149948387']</value>
      <webElementGuid>b3e8ada9-f9b8-4a4d-92d2-a66dc02688cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
