<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textfield-1021</name>
   <tag></tag>
   <elementGuidId>34aa1de0-04ff-45c0-99d4-1de5799e95ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textfield-1021-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textfield-1021-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4479807f-4a7e-4342-be99-69eac2e4fb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textfield-1021-inputEl</value>
      <webElementGuid>cdd7f899-5b1b-4ac4-8568-199a5d8035a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>f88674b1-b40c-4224-9017-370877a8ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a8def76-3449-4384-9a17-05fa73cdfe38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c2881ff-db53-40b2-8572-e0a60cf5c61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textfield-1021</value>
      <webElementGuid>45473019-aad3-45c7-90be-947068547f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c058ddd6-09e1-4e42-8d59-bc12ce7d384c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6cd4d02a-04cd-47ae-a9c2-1240f1dae3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b5a1516f-94ac-4091-9309-339af7625d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a18febc6-c64a-42ed-b3ce-45edda1ca29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>071813ab-4b18-4d46-a09b-a8725010a383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textfield-1021-ariaStatusEl</value>
      <webElementGuid>950c56ea-b77a-4ace-9184-156685282121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b973808-1d48-4ddd-8ced-5d90cbdf4e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-text-default  x-clear-field x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>5e52041c-3f2d-4133-b0aa-f52076cb3531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e7cd331f-f3b4-4206-8785-8795ec3c2ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>textfield-1021</value>
      <webElementGuid>b48221a8-8330-492d-8ed4-907d8c3406cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textfield-1021-inputEl&quot;)</value>
      <webElementGuid>71ebc8de-8f08-4df2-ad7b-ddf802ce512f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/searchingtransactionfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>b20cc028-a0e9-4241-9ee9-0c0c75398441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textfield-1021-inputEl']</value>
      <webElementGuid>2547e470-669e-45cf-b43d-8fd8fe745e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textfield-1021-inputWrap']/input</value>
      <webElementGuid>0ed80a47-9060-4fd4-83c7-7e8f86d47d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>f57492d1-41f7-4d09-926f-9607e670bb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textfield-1021-inputEl' and @type = 'text' and @name = 'textfield-1021']</value>
      <webElementGuid>f72113a2-706c-4198-8d7f-fc7baec08dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
