<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divContentPlaceHolder1_AdvancedFilter1_cboF_b58eab</name>
   <tag></tag>
   <elementGuidId>147d3ca4-47de-4830-a01e-5d5f9e0e3dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8c5e49f-6d10-47ba-b9ed-3980c54cb734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker</value>
      <webElementGuid>7148bae4-9fc4-411a-ae02-fb424e8d6edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>842cf0aa-2b51-43d0-bd01-2d67d4c1266c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>185df43a-da8d-4e6e-b9f0-eee2a76427f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker&quot;)</value>
      <webElementGuid>a7e3fa81-31e4-4274-9293-888dc3193601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/advancedfilterfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>228d2c4e-deec-48b9-acb8-0b76be801766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      <webElementGuid>1cc56644-96d5-40f3-81e4-48c1dedcf2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-triggerWrap']/div[3]</value>
      <webElementGuid>40160a26-27b2-40ec-8c36-6f5cfa0f4ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>554498fd-5491-4fbd-ada6-0af0f25c1493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      <webElementGuid>ccefdf4a-9135-4e7c-aa2c-4b89a532e6ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
