<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Employee ID</name>
   <tag></tag>
   <elementGuidId>10c9d883-6249-427c-9112-abcb5ff874e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ext-element-76']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-76</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Employee ID' or . = 'Employee ID') and @ref_element = 'Object Repository/advancedfilterfailed/iframe_nodeundefined_IFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>41cb638e-ff3b-4ff6-a943-ed4e0556077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f0fa661d-9811-416b-9588-94d289a1aa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2a990cb7-d62b-4e79-a9bb-287a1916cce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>c2365b86-9a54-4c26-8896-7afc06103289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>735929cb-2ae7-42c5-b86d-e6333c4f584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>deae76cd-845d-4ec8-8934-6721d80a3ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>26471cf1-a1f7-46d8-9002-fb86542bdfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboField-picker</value>
      <webElementGuid>14733546-c3bc-44f9-b9ba-7ecd6ad988ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-76</value>
      <webElementGuid>35335a4c-6b2c-4d81-abec-c34fa8054fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee ID</value>
      <webElementGuid>15478709-1f7d-4254-b283-a667773e0af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-76&quot;)</value>
      <webElementGuid>8bac7daa-d697-4abc-95f0-fe03df7efdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/advancedfilterfailed/iframe_nodeundefined_IFrame</value>
      <webElementGuid>e3b36fde-0659-4fb1-987c-0e1db0d3670f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-76']</value>
      <webElementGuid>3b9c0d7a-1b1b-43bf-aa45-bb1be93e20d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-picker-listEl']/li</value>
      <webElementGuid>154bd3f7-bd70-4101-8880-76cc3ee0b041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>e7d8d38c-85ad-4bc4-a0aa-adc7c52a7c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-76' and (text() = 'Employee ID' or . = 'Employee ID')]</value>
      <webElementGuid>790740e0-997c-43b9-b019-36e040f43c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
